// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function find(arr, func) {
  var result = /* record */[/* contents : False */0];
  $$Array.iteri((function (index, v) {
          if (Curry._1(func, v)) {
            result[0] = /* True */[
              v,
              index
            ];
            return /* () */0;
          } else {
            result[0] = /* False */0;
            return /* () */0;
          }
        }), arr);
  return result[0];
}

function findO(arr, func) {
  var result = /* record */[/* contents : False */0];
  $$Array.iteri((function (index, v) {
          if (v !== undefined) {
            var v$1 = Js_primitive.valFromOption(v);
            if (Curry._1(func, v$1)) {
              result[0] = /* True */[
                v$1,
                index
              ];
              return /* () */0;
            } else {
              result[0] = /* False */0;
              return /* () */0;
            }
          } else {
            result[0] = /* False */0;
            return /* () */0;
          }
        }), arr);
  return result[0];
}

exports.find = find;
exports.findO = findO;
/* No side effect */
