// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function getMsgContents(msg) {
  return /* record */[
          /* action */Json_decode.field("action", Json_decode.string, Json.parseOrRaise(msg)),
          /* id */Caml_format.caml_int_of_string(Json_decode.field("id", Json_decode.string, Json.parseOrRaise(msg)))
        ];
}

function decodeMsg(msg) {
  console.log(1);
  var contents = getMsgContents(msg);
  console.log(1);
  var match = contents[/* action */0];
  if (match === "createGame") {
    return /* CreateGame */[contents[/* id */1]];
  } else {
    return /* None */0;
  }
}

exports.getMsgContents = getMsgContents;
exports.decodeMsg = decodeMsg;
/* No side effect */
