// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function doMsg(msg) {
  if (msg) {
    return /* CreateGameFailed */Block.__(1, [/* Error */0]);
  } else {
    return /* None */0;
  }
}

exports.doMsg = doMsg;
/* No side effect */
