// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var maxGameId = /* record */[/* contents */-1];

var overGamesId = /* record */[/* contents : [] */0];

var games = Caml_array.caml_make_vect(10, undefined);

function setNewGameId() {
  var match = overGamesId[0];
  if (match) {
    overGamesId[0] = match[1];
    return match[0];
  } else {
    maxGameId[0] = maxGameId[0] + 1 | 0;
    return maxGameId[0];
  }
}

function createGame(id) {
  var gameId = setNewGameId(/* () */0);
  var newGame_001 = /* players : array */[/* record */[
      /* id */id,
      /* position : tuple */[
        0.1,
        0.1
      ],
      /* shootSpeed */0.3,
      /* rotateVec */0.3,
      /* rotataRange : tuple */[
        0.0,
        0.75
      ],
      /* boundingBox : tuple */[
        0.05,
        0.05
      ]
    ]];
  var newGame = /* record */[
    /* id */gameId,
    newGame_001,
    /* actPlayer */id
  ];
  Caml_array.caml_array_set(games, gameId, newGame);
  return newGame;
}

function endGame(id) {
  Caml_array.caml_array_set(games, id, undefined);
  overGamesId[0] = /* :: */[
    id,
    overGamesId[0]
  ];
  return /* () */0;
}

exports.maxGameId = maxGameId;
exports.overGamesId = overGamesId;
exports.games = games;
exports.setNewGameId = setNewGameId;
exports.createGame = createGame;
exports.endGame = endGame;
/* No side effect */
