// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ManageId$Game = require("./manageId.bs.js");

var match = ManageId$Game.initIdManagement(/* () */0);

var recycleId = match[1];

var getId = match[0];

var games = Caml_array.caml_make_vect(10, undefined);

function createGame(id) {
  var gameId = Curry._1(getId, /* () */0);
  var newGame_001 = /* players : array */[/* record */[
      /* id */id,
      /* position : tuple */[
        0.1,
        0.1
      ],
      /* shootSpeed */0.3,
      /* rotateVec */0.3,
      /* rotataRange : tuple */[
        0.0,
        0.75
      ],
      /* boundingBox : tuple */[
        0.05,
        0.05
      ]
    ]];
  var newGame = /* record */[
    /* id */gameId,
    newGame_001,
    /* actPlayer */id
  ];
  Caml_array.caml_array_set(games, gameId, newGame);
  return newGame;
}

function endGame(id) {
  Curry._1(recycleId, id);
  return Caml_array.caml_array_set(games, id, undefined);
}

exports.getId = getId;
exports.recycleId = recycleId;
exports.games = games;
exports.createGame = createGame;
exports.endGame = endGame;
/* match Not a pure module */
