// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function getCodeInt(code) {
  if (code) {
    return 304;
  } else {
    return 404;
  }
}

function makeResponse(result) {
  if (typeof result === "number") {
    return "doNotAct";
  } else if (result.tag) {
    return "error code" + String(result[0] ? 304 : 404);
  } else {
    var game = result[0];
    return Json_encode.object_(/* :: */[
                /* tuple */[
                  "id",
                  Json.parseOrRaise(String(game[/* id */0]))
                ],
                /* :: */[
                  /* tuple */[
                    "actPlayer",
                    Json.parseOrRaise(String(game[/* actPlayer */2]))
                  ],
                  /* [] */0
                ]
              ]);
  }
}

exports.getCodeInt = getCodeInt;
exports.makeResponse = makeResponse;
/* Json_encode Not a pure module */
