// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var DoMsg$Game = require("./doMsg.bs.js");
var DecodeMsg$Game = require("./decodeMsg.bs.js");
var MakeResponse$Game = require("./makeResponse.bs.js");

var msg = " { \"action\": \"createDesk\", \"id\": \"1\" } ";

console.log(JSON.stringify(MakeResponse$Game.makeResponse(DoMsg$Game.doMsg(DecodeMsg$Game.decodeMsg(msg)))));

exports.msg = msg;
/*  Not a pure module */
