// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function createUser() {
  return /* record */[
          /* id */"a",
          /* name */"asd"
        ];
}

exports.createUser = createUser;
/* No side effect */
