// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function createUser() {
  return /* record */[
          /* id */1,
          /* name */"asd"
        ];
}

exports.createUser = createUser;
/* No side effect */
