// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

function createUser() {
  return /* record */[
          /* id */"a",
          /* name */"asd"
        ];
}

exports.createUser = createUser;
/*  Not a pure module */
